Update Jenkinsfile

diff --git a/Docker-app/Jenkinsfile b/Docker-app/Jenkinsfile
--- a/Docker-app/Jenkinsfile
+++ b/Docker-app/Jenkinsfile
@@ -1,58 +1,13 @@
 pipeline {
     agent any
-    
-    environment {
-        DOCKER_HUB_CREDS = credentials('dockerhub-creds') // Jenkins credentials ID for Docker Hub
-        DOCKER_IMAGE = "naveenbalagouni/my-python-app"
-    }
-
     stages {
-        stage('Checkout Code') {
+        stage('Check Docker') {
             steps {
-                // Checkout the code from GitHub
-                git credentialsId: 'your-github-credentials-id', branch: 'main', url: 'https://github.com/NaveenBalagouni/ssd-pratice.git'
-
+                sh 'echo $PATH'
+                sh 'ls -l /usr/bin/docker'
+                sh 'which docker || echo "Docker not found"'
+                sh 'docker --version || echo "Docker CLI not available"'
             }
-        }
-        
-        stage('Build Docker Image') {
-            steps {
-                script {
-                    // Login to Docker Hub
-                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
-                        sh 'docker --version'  // Check Docker version to ensure Docker is available
-                        sh """
-                            echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin
-                            docker build -t \$DOCKER_IMAGE:latest .
-                        """
-                    }
-                }
-            }
-        }
-
-        stage('Push Docker Image to Docker Hub') {
-            steps {
-                script {
-                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
-                        sh """
-                            docker push \$DOCKER_IMAGE:latest
-                        """
-                    }
-                }
-            }
-        }
-    }
-
-    post {
-        always {
-            // Clean up after the build
-            cleanWs()
-        }
-        success {
-            echo 'Docker image built and pushed successfully!'
-        }
-        failure {
-            echo 'There was an error during the build or push process.'
         }
     }
 }
